# Generated by Django 4.1.3 on 2022-11-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msbooks_books', '0004_language_alter_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
