# Generated by Django 4.1.3 on 2022-11-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbooks_books', '0006_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
