# Generated by Django 4.1.3 on 2022-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbooks_books', '0007_alter_bookimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(upload_to='books_images'),
        ),
    ]
