# Generated by Django 4.1.3 on 2022-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbooks_books', '0010_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
