# Generated by Django 4.1.3 on 2022-11-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbooks_books', '0012_alter_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
