# Generated by Django 4.1.3 on 2022-11-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msbooks_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinorder',
            options={'verbose_name': 'книга в заказе', 'verbose_name_plural': 'книги в заказе'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'статус', 'verbose_name_plural': 'статусы'},
        ),
    ]
