# Generated by Django 4.1.3 on 2022-11-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbooks_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'подписчик', 'verbose_name_plural': 'подписчики'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
    ]
